Allow users to set container security context (new)
solo-io/skv2 pull request #346
Opened 2022-06-13 15:38 UTC by jmhbh

**Overview**
* Original [PR](https://github.com/solo-io/skv2/pull/342) was merged accidentally this is the new PR
* In this [issue](https://github.com/solo-io/gloo-mesh-enterprise/issues/4000) the ask is to allow the user to omit container `securityContext` using helm's `--set` options when running helm install for the GME enterprise chart specifically to omit the container `securityContext` for the `glooMeshRedis` container.
* Because the GME helm charts are generated via SKV2. In order to address this, the change in this PR allows the container `securityContext` to be overridden and modifies the  `codegen/templates/chart/operator-deployment.yamltmpl` file to conditionally render the override `securityContext` configurations if it exists or is an empty map. In order to support the user needing to omit the `securityContext` via the helm cli we will also check to see if `securityContext` is false and render an empty map if so (this will support the user appending `--set glooMeshRedis.securityContext=false` to their helm install command). Otherwise the default container security context config is rendered. 
* For more context into why this approach was taken please refer to my comment on the issue [here](https://github.com/solo-io/gloo-mesh-enterprise/issues/4000#issuecomment-1149955422)

2022-06-13 21:20 UTC, jmhbh commented
> This approach looks good, but I'm seeing errors like:
> 
> ```
> Error: template: gloo-mesh-enterprise/templates/deployment.yaml:111:3: executing "gloo-mesh-enterprise/templates/deployment.yaml" at <include "skv2.utils.merge" (list . $glooMeshMgmtServerDeploymentOverrides "gloo-mesh-mgmt-server.deploymentSpec")>: error calling include: template: gloo-mesh-enterprise/templates/_helpers.tpl:47:22: executing "skv2.utils.merge" at <include (index . 2) $top>: error calling include: template: gloo-mesh-enterprise/templates/deployment.yaml:85:12: executing "gloo-mesh-mgmt-server.deploymentSpec" at <eq false $glooMeshMgmtServer.securityContext>: error calling eq: invalid type for comparison
> make: *** [Makefile:342: setup-test-clusters] Error 1
> ```
> 
> on the GME PR [solo-io/gloo-mesh-enterprise#4083](https://github.com/solo-io/gloo-mesh-enterprise/pull/4083)
> 
> This PR should stay open until the GME PR passes, and then I can approve both.

Thanks for your comments @ashleywang1! I fixed this issue as can be seen in the helm test workflow in my GME [PR](https://github.com/solo-io/gloo-mesh-enterprise/pull/4083). Also addressed your other comments.

2022-06-14 13:22 UTC, ashleywang1 requested changes

2022-06-14 13:22 UTC, ashleywang1 commented on codegen/model/values/helm_chart_values.go
> +	SecurityContext *v1.SecurityContext      `json:"securityContext,omitempty" desc:"Specify container security context. See the [Kubernetes documentation](https://kubernetes.io/docs/reference/generated
```suggestion
	SecurityContext *v1.SecurityContext      `json:"securityContext,omitempty" desc:"Specify container security context. Set to 'false' to omit the security context entirely. See the [Kubernetes documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#securitycontext-v1-core) for specification details. Can be set to false to omit rendering of securityContext for the container."`
```

2022-06-14 13:22 UTC, ashleywang1 commented on codegen/model/values/helm_chart_values.go
> +	SecurityContext *v1.SecurityContext      `json:"securityContext,omitempty" desc:"Specify container security context. See the [Kubernetes documentation](https://kubernetes.io/docs/reference/generated
Here and below

2022-06-14 13:31 UTC, jmhbh commented on codegen/model/values/helm_chart_values.go
> +	SecurityContext *v1.SecurityContext      `json:"securityContext,omitempty" desc:"Specify container security context. See the [Kubernetes documentation](https://kubernetes.io/docs/reference/generated
fixed

2022-06-14 14:22 UTC, ashleywang1 approved these changes

2022-06-14 14:22 UTC, merged